# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ifd-b9kyaXY30bnApdXcQXI0gBacRxlq
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile project_repo/src/eda.py
# import pandas as pd
# import seaborn as sns
# import matplotlib.pyplot as plt
# import os
# 
# # Define Inputs/Outputs
# INPUT_FILE = 'project_repo/data/processed/cleaned_spotify_tracks.csv'
# OUTPUT_DIR = 'project_repo/results'
# 
# def run_eda():
#     print("--- Starting Exploratory Data Analysis (EDA) ---")
# 
#     # 0. Setup
#     if not os.path.exists(INPUT_FILE):
#         print(f"❌ Error: Input file not found at {INPUT_FILE}")
#         return
# 
#     df = pd.read_csv(INPUT_FILE)
#     os.makedirs(OUTPUT_DIR, exist_ok=True)
# 
#     # Set style
#     sns.set_theme(style="whitegrid")
# 
#     # --- 10 DISTINCT EDA OPERATIONS ---
# 
#     # 1. Descriptive Statistics (The "Five Number Summary")
#     # Reason: Check central tendency and spread.
#     desc_stats = df.describe()
#     desc_stats.to_csv(f"{OUTPUT_DIR}/1_descriptive_statistics.csv")
#     print("1. Saved descriptive statistics.")
# 
#     # 2. Correlation Heatmap (Multivariate Analysis)
#     # Reason: Identify collinearity between audio features.
#     plt.figure(figsize=(12, 10))
#     # Select only numeric columns for correlation
#     numeric_df = df.select_dtypes(include=['float64', 'int64'])
#     corr = numeric_df.corr()
#     sns.heatmap(corr, annot=False, cmap='coolwarm', vmin=-1, vmax=1)
#     plt.title("Feature Correlation Matrix")
#     plt.tight_layout()
#     plt.savefig(f"{OUTPUT_DIR}/2_correlation_heatmap.png")
#     plt.close()
#     print("2. Saved correlation heatmap.")
# 
#     # 3. Distribution of Popularity (Univariate Analysis)
#     # Reason: Check if target variable is normal or skewed.
#     plt.figure(figsize=(10, 6))
#     sns.histplot(df['popularity'], bins=30, kde=True, color='purple')
#     plt.title("Distribution of Track Popularity")
#     plt.savefig(f"{OUTPUT_DIR}/3_popularity_distribution.png")
#     plt.close()
#     print("3. Saved popularity distribution.")
# 
#     # 4. Danceability vs. Energy (Bivariate Analysis)
#     # Reason: Test hypothesis that danceable songs are energetic.
#     plt.figure(figsize=(10, 6))
#     sns.scatterplot(data=df.sample(min(1000, len(df))), x='danceability', y='energy', alpha=0.5)
#     plt.title("Danceability vs Energy (Sampled)")
#     plt.savefig(f"{OUTPUT_DIR}/4_dance_vs_energy_scatter.png")
#     plt.close()
#     print("4. Saved scatter plot.")
# 
#     # 5. Boxplot: Duration by Popularity Tier (Categorical vs Numerical)
#     # Reason: Do popular songs tend to be shorter?
#     if 'popularity_tier' in df.columns and 'duration_mins' in df.columns:
#         plt.figure(figsize=(10, 6))
#         sns.boxplot(x='popularity_tier', y='duration_mins', data=df, palette="Set2")
#         plt.title("Song Duration by Popularity Tier")
#         plt.savefig(f"{OUTPUT_DIR}/5_duration_boxplot.png")
#         plt.close()
#         print("5. Saved boxplot.")
# 
#     # 6. Count Plot: Explicit Content
#     # Reason: Check class imbalance for explicit tracks.
#     if 'is_explicit' in df.columns:
#         plt.figure(figsize=(6, 4))
#         sns.countplot(x='is_explicit', data=df)
#         plt.title("Count of Explicit vs Non-Explicit Tracks")
#         plt.savefig(f"{OUTPUT_DIR}/6_explicit_count.png")
#         plt.close()
#         print("6. Saved count plot.")
# 
#     # 7. Violin Plot: Loudness Distribution
#     # Reason: Visualize density and outliers of loudness.
#     plt.figure(figsize=(10, 6))
#     sns.violinplot(x=df['loudness'], color='orange')
#     plt.title("Violin Plot of Loudness")
#     plt.savefig(f"{OUTPUT_DIR}/7_loudness_violin.png")
#     plt.close()
#     print("7. Saved violin plot.")
# 
#     # 8. Time Signature Analysis (Bar Chart)
#     # Reason: See common structures in the data.
#     # Note: Using One-Hot columns if they exist, else raw
#     ts_cols = [c for c in df.columns if 'ts_' in c]
#     if ts_cols:
#         ts_sums = df[ts_cols].sum().sort_values(ascending=False)
#         plt.figure(figsize=(10, 6))
#         ts_sums.plot(kind='bar', color='teal')
#         plt.title("Count of Tracks by Time Signature")
#         plt.savefig(f"{OUTPUT_DIR}/8_time_signature_counts.png")
#         plt.close()
#         print("8. Saved time signature analysis.")
# 
#     # 9. Hexbin Plot: Valence vs. Danceability
#     # Reason: Better for dense data than scatter plots.
#     plt.figure(figsize=(10, 8))
#     plt.hexbin(df['valence'], df['danceability'], gridsize=20, cmap='Blues')
#     plt.colorbar(label='Count')
#     plt.title("Hexbin: Valence (Mood) vs Danceability")
#     plt.savefig(f"{OUTPUT_DIR}/9_mood_dance_hexbin.png")
#     plt.close()
#     print("9. Saved hexbin plot.")
# 
#     # 10. Pairplot (Multivariate Overview)
#     # Reason: Quick view of interactions between key metrics.
#     subset_cols = ['popularity', 'energy', 'acousticness', 'instrumentalness']
#     # Filter for existing columns
#     subset_cols = [c for c in subset_cols if c in df.columns]
#     if subset_cols:
#         subset = df[subset_cols].sample(min(500, len(df))) # Sample for speed
#         pp = sns.pairplot(subset, corner=True)
#         pp.savefig(f"{OUTPUT_DIR}/10_key_features_pairplot.png")
#         print("10. Saved pairplot.")
# 
#     print(f"✅ EDA Complete. Images saved to {OUTPUT_DIR}")
# 
# if __name__ == "__main__":
#     run_eda()
#